export const CHANGE_TABS_KEY = 'CHANGE_TABS_KEY'
export const ADD_ITEM = 'ADD_ITEM'
export const CHANGE_ITEM = 'CHANGE_ITEM'
export const CHOOSE_OBJECT = 'CHOOSE_OBJECT'
export const CHOOSE_ELE = 'CHOOSE_ELE'
